name: Testes da API da Marvel 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    environment:
      name: Produção
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: devops-actions/json-to-file@v1.0.0
        with:
          json: ${{ secrets.CYPRESS_ENV }}
          filename: 'cypress.env.json'
      - name: Execute Shell Script
        run: |
          chmod +x ./back2thepast.sh
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4